-- Familia Food
-- Tabel yang memang belum ada: pengaturan.
-- Jalankan SQL ini SATU KALI di Supabase SQL Editor.

create table if not exists public.pengaturan (
  id bigint generated by default as identity primary key,
  nama_usaha text not null default 'Familia Food',
  logo text,
  warna text not null default '#087443',
  admin text,
  updated_at timestamptz not null default now()
);

-- Sengaja tidak mengubah tabel produk/hpp/penjualan/data_lama.
-- Sengaja tidak mengaktifkan/menonaktifkan RLS pada tabel yang sudah ada.
