-- Familia Food — Expansion aman, tidak mengubah tabel lama.
-- Modul: Supplier, Pembelian, Pelanggan, Retur Penjualan.
-- Tidak membuat/menyentuh stok, mutasi stok, pembayaran, multi-outlet, atau user/role.

create table if not exists public.ff_supplier (
  id bigint generated by default as identity primary key,
  nama text not null,
  telepon text,
  alamat text,
  catatan text,
  status text not null default 'Aktif',
  created_at timestamptz not null default now()
);

create table if not exists public.ff_pelanggan (
  id bigint generated by default as identity primary key,
  nama text not null,
  telepon text,
  alamat text,
  catatan text,
  status text not null default 'Aktif',
  created_at timestamptz not null default now()
);

create table if not exists public.ff_pembelian (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  supplier_id bigint references public.ff_supplier(id) on delete set null,
  total numeric not null default 0,
  catatan text,
  created_at timestamptz not null default now()
);

create table if not exists public.ff_pembelian_item (
  id bigint generated by default as identity primary key,
  pembelian_id bigint not null references public.ff_pembelian(id) on delete cascade,
  bahan_id bigint references public.bahan_baku(id) on delete set null,
  nama_bahan text not null,
  qty numeric not null default 0,
  satuan text,
  harga_beli numeric not null default 0,
  subtotal numeric not null default 0,
  catatan text
);

create table if not exists public.ff_retur_penjualan (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  penjualan_id bigint references public.penjualan(id) on delete set null,
  channel text not null default 'Offline',
  produk_id bigint references public.produk(id) on delete set null,
  nama_produk text not null,
  qty numeric not null default 0,
  nominal numeric not null default 0,
  alasan text,
  created_at timestamptz not null default now()
);

create table if not exists public.ff_penjualan_pelanggan (
  id bigint generated by default as identity primary key,
  penjualan_id bigint not null unique references public.penjualan(id) on delete cascade,
  pelanggan_id bigint not null references public.ff_pelanggan(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists ff_pelanggan_map_pelanggan_idx on public.ff_penjualan_pelanggan(pelanggan_id);
create index if not exists ff_pembelian_tanggal_idx on public.ff_pembelian(tanggal);
create index if not exists ff_pembelian_item_pembelian_idx on public.ff_pembelian_item(pembelian_id);
create index if not exists ff_retur_tanggal_idx on public.ff_retur_penjualan(tanggal);

-- Familia Food saat ini memakai Supabase client langsung tanpa login.
-- Beri akses Data API ke role yang dipakai client dan tooling Supabase.
grant select, insert, update, delete on table
  public.ff_supplier,
  public.ff_pelanggan,
  public.ff_pembelian,
  public.ff_pembelian_item,
  public.ff_retur_penjualan,
  public.ff_penjualan_pelanggan
to anon, authenticated, service_role;

grant usage, select on sequence
  public.ff_supplier_id_seq,
  public.ff_pelanggan_id_seq,
  public.ff_pembelian_id_seq,
  public.ff_pembelian_item_id_seq,
  public.ff_retur_penjualan_id_seq,
  public.ff_penjualan_pelanggan_id_seq
to anon, authenticated, service_role;

-- Mapping pelanggan↔penjualan adalah tabel tambahan; tabel penjualan inti tetap tidak diubah.
-- Sengaja tidak mengubah struktur produk, bahan_baku, resep, hpp, penjualan,
-- data_lama, pengeluaran, atau pengaturan yang sudah dipakai Familia Food.
